import { Problem, Submission } from '../parser/types';

export class ReadmeGenerator {
  /**
   * Generates a beautifully formatted markdown documentation page for the problem and submission.
   */
  static generate(problem: Problem, submission: Submission): string {
    const badgeColor = this.getDifficultyColor(problem.difficulty);
    const dateStr = new Date(submission.timestamp).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    return `# [${problem.title}](${problem.url})

## Metadata
- **Difficulty:** <span style="color: ${badgeColor}; font-weight: bold;">${problem.difficulty}</span>
- **Language:** \`${submission.language}\`
- **Submission Date:** ${dateStr}
${problem.tags.length > 0 ? `- **Tags:** ${problem.tags.map(t => `\`${t}\``).join(', ')}` : ''}

## Description
${problem.description}

## Solution
\`\`\`${this.getMarkdownLanguage(submission.language)}
${submission.code}
\`\`\`

---
*Autogenerated by [CodeSync](https://github.com/pardeep1916P/codeSync).*
`;
  }

  private static getDifficultyColor(difficulty: 'Easy' | 'Medium' | 'Hard'): string {
    switch (difficulty) {
      case 'Easy':
        return '#22c55e'; // Green-500
      case 'Medium':
        return '#eab308'; // Yellow-500
      case 'Hard':
        return '#ef4444'; // Red-500
      default:
        return '#6b7280';
    }
  }

  private static getMarkdownLanguage(lang: string): string {
    const clean = lang.toLowerCase().trim();
    if (clean === 'cpp' || clean === 'c++') return 'cpp';
    if (clean === 'javascript' || clean === 'js') return 'javascript';
    if (clean === 'typescript' || clean === 'ts') return 'typescript';
    if (clean === 'python' || clean === 'py' || clean === 'python3') return 'python';
    if (clean === 'java') return 'java';
    if (clean === 'golang' || clean === 'go') return 'go';
    if (clean === 'rust' || clean === 'rs') return 'rust';
    return clean;
  }
}
