import { Problem, Submission } from '../parser/types';
import { getLanguageDisplayName, getMarkdownLanguage } from '../utils/languages';

export class ReadmeGenerator {
  /**
   * Generates a beautifully formatted markdown documentation page for the problem and submission.
   */
  static generate(problem: Problem, submission: Submission, existingContent: string | null = null): string {
    const badgeColor = this.getDifficultyColor(problem.difficulty);
    const dateStr = new Date(submission.timestamp).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    const newLangDisplay = getLanguageDisplayName(submission.language);
    const newLangId = getMarkdownLanguage(submission.language);
    const newCode = submission.code.trim();

    // Map to keep track of language -> code
    const solutionsMap = new Map<string, { langId: string; code: string }>();

    let description = problem.description;

    if (existingContent) {
      // 1. Try to extract description from existing README
      // Description is usually between ## Description and ## Solution (or ## Solutions)
      const descMatch = existingContent.match(/## Description\n([\s\S]*?)\n## Solution/i);
      if (descMatch) {
        description = descMatch[1].trim();
      }

      // 2. Try to parse existing solutions
      // Format 1: With "### Language" headings
      // Format 2: Legacy format (direct code block under ## Solution)
      const solutionSectionMatch = existingContent.match(/## Solution[s]?\n([\s\S]*?)(?:\n---\n\*Autogenerated|$)/i);
      if (solutionSectionMatch) {
        const solutionSection = solutionSectionMatch[1].trim();
        if (solutionSection.includes('### ')) {
          // Format 1: Split by "### "
          const parts = solutionSection.split(/###\s+/);
          for (const part of parts) {
            if (!part.trim()) continue;
            const lines = part.split('\n');
            const langName = lines[0].trim();
            const codeBlock = lines.slice(1).join('\n').trim();
            const codeMatch = codeBlock.match(/```(\w*)\n([\s\S]*?)```/);
            if (codeMatch) {
              solutionsMap.set(langName, {
                langId: codeMatch[1],
                code: codeMatch[2].trim()
              });
            }
          }
        } else {
          // Format 2: Legacy direct code block
          const codeMatch = solutionSection.match(/```(\w*)\n([\s\S]*?)```/);
          if (codeMatch) {
            let langName = '';
            const langMetaMatch = existingContent.match(/-\s+\*\*Language:\*\*\s+`([^`]+)`/i);
            if (langMetaMatch) {
              langName = getLanguageDisplayName(langMetaMatch[1]);
            } else {
              langName = getLanguageDisplayName(codeMatch[1]);
            }
            solutionsMap.set(langName, {
              langId: codeMatch[1],
              code: codeMatch[2].trim()
            });
          }
        }
      }
    }

    // Add or overwrite the new solution
    solutionsMap.set(newLangDisplay, {
      langId: newLangId,
      code: newCode
    });

    // Sort languages alphabetically
    const sortedLanguages = Array.from(solutionsMap.keys()).sort();

    // Reconstruct Languages list for Metadata
    const languagesStr = sortedLanguages.map(l => `\`${l}\``).join(', ');

    // Reconstruct Solution Section
    let solutionSectionStr = '## Solution\n';
    for (const lang of sortedLanguages) {
      const sol = solutionsMap.get(lang)!;
      solutionSectionStr += `\n### ${lang}\n\`\`\`${sol.langId}\n${sol.code}\n\`\`\`\n`;
    }

    return `# [${problem.title}](${problem.url})

## Metadata
- **Difficulty:** <span style="color: ${badgeColor}; font-weight: bold;">${problem.difficulty}</span>
- **Languages:** ${languagesStr}
- **Submission Date:** ${dateStr}
${problem.tags.length > 0 ? `- **Tags:** ${problem.tags.map(t => `\`${t}\``).join(', ')}` : ''}

## Description
${description}

${solutionSectionStr}
---
*Autogenerated by [CodeSync](https://github.com/pardeep1916P/codeSync).*
`;
  }

  private static getDifficultyColor(difficulty: 'Easy' | 'Medium' | 'Hard'): string {
    switch (difficulty) {
      case 'Easy':
        return '#22c55e'; // Green-500
      case 'Medium':
        return '#eab308'; // Yellow-500
      case 'Hard':
        return '#ef4444'; // Red-500
      default:
        return '#6b7280';
    }
  }
}
