import { describe, it, expect } from 'vitest';
import { ReadmeGenerator } from '../index';
import { Problem, Submission } from '../../parser/types';

describe('ReadmeGenerator with Multi-Language Support', () => {
  const mockProblem: Problem = {
    id: 'two-sum',
    title: 'Two Sum',
    slug: 'two-sum',
    difficulty: 'Easy',
    description: 'Given an array of integers, return indices of the two numbers.',
    tags: ['Array', 'Hash Table'],
    url: 'https://leetcode.com/problems/two-sum/',
  };

  const cppSubmission: Submission = {
    id: 'sub_cpp',
    problem: mockProblem,
    language: 'cpp',
    code: 'class Solution {};',
    timestamp: 1783680000000,
    status: 'ACCEPTED',
  };

  const javaSubmission: Submission = {
    id: 'sub_java',
    problem: mockProblem,
    language: 'java',
    code: 'class JavaSolution {}',
    timestamp: 1783690000000,
    status: 'ACCEPTED',
  };

  it('should generate a beautiful initial markdown page for a single language solution', () => {
    const result = ReadmeGenerator.generate(mockProblem, cppSubmission);

    expect(result).toContain('# [Two Sum](https://leetcode.com/problems/two-sum/)');
    expect(result).toContain('**Difficulty:** <span style="color: #22c55e; font-weight: bold;">Easy</span>');
    expect(result).toContain('**Languages:** `C++`');
    expect(result).toContain('### C++');
    expect(result).toContain('```cpp\nclass Solution {};\n```');
  });

  it('should append and merge a new language solution to an existing multi-language README', () => {
    const initialReadme = ReadmeGenerator.generate(mockProblem, cppSubmission);
    const updatedReadme = ReadmeGenerator.generate(mockProblem, javaSubmission, initialReadme);

    // Verify both languages are listed in metadata
    expect(updatedReadme).toContain('**Languages:** `C++`, `Java`');

    // Verify both solutions are present under language headings
    expect(updatedReadme).toContain('### C++');
    expect(updatedReadme).toContain('```cpp\nclass Solution {};\n```');
    expect(updatedReadme).toContain('### Java');
    expect(updatedReadme).toContain('```java\nclass JavaSolution {}\n```');
  });

  it('should migrate a legacy README format with a direct code block to the new format', () => {
    const legacyReadme = `# [Two Sum](https://leetcode.com/problems/two-sum/)

## Metadata
- **Difficulty:** <span style="color: #22c55e; font-weight: bold;">Easy</span>
- **Language:** \`cpp\`
- **Submission Date:** July 10, 2026

## Description
Given an array of integers, return indices of the two numbers.

## Solution
\`\`\`cpp
class Solution {};
\`\`\`

---
*Autogenerated by [CodeSync](https://github.com/pardeep1916P/codeSync).*
`;

    const updatedReadme = ReadmeGenerator.generate(mockProblem, javaSubmission, legacyReadme);

    // Verify migration to C++ and Java
    expect(updatedReadme).toContain('**Languages:** `C++`, `Java`');
    expect(updatedReadme).toContain('### C++');
    expect(updatedReadme).toContain('```cpp\nclass Solution {};\n```');
    expect(updatedReadme).toContain('### Java');
    expect(updatedReadme).toContain('```java\nclass JavaSolution {}\n```');
  });
});
